services:
  gguf-accuracy-test:
    build: .
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]